defaults:
  - alphafold_config

# Model fine-tuned from "deepmind-casp14_monomer_1" model
# with an additional predicted_aligned_error head that can produce
# predicted TM-score (pTM) and predicted aligned errors.
data:
  common:
    max_extra_msa: 5120
    reduce_msa_clusters_by_max_templates: True
    use_templates: True
model:
  embeddings_and_evoformer:
    template:
      embed_torsion_angles: True
      enabled: True
  heads:
    predicted_aligned_error:
      weight: 0.1
