defaults:
  - alphafold_config

# Jumper et al. (2021) Suppl. Table 5, Model 1.1.1
data:
  common:
    max_extra_msa: 5120
    reduce_msa_clusters_by_max_templates: True
    use_templates: True
model:
  embeddings_and_evoformer:
    template:
      embed_torsion_angles: True
      enabled: True
